### PR TITLE
Possible fixes for issue #42

### PR DESCRIPTION
**Pull request by winsock**
Unless I do not understand the USB stack at all, shouldn't this work while simplifying the matching code? I also have a unsigned test kext for those of you that have rootless setup to test.

Edit:
Oops, it would help to change some variables around :P
Updated non-signed kext for 10.9+ 64bit
https://drive.google.com/file/d/0B-1JrQBHFxtGN20xcWJXbE9lb2M/view?usp=sharing

### CODE REVIEW

**Comment by winsock** [comment]
# Note, my PR is UNTESTED since my android phone broke and the backup is an iPhone 4.

**Comment by jwise** [comment]
Oh, this is promising!  Ok, lots of things make sense now.  I haven't tried it myself yet, but this is certainly an interesting idea that gives me things to look at.  I'm pretty busy on weeknights, but hopefully I'll have some bandwidth for this either Thursday night or at the latest on the weekend.  Someone also has sent me a device that in theory repro sthe issue, which UPS says will arrive on Thursday, too.  So all things might converge.  We'll see.  Thanks for the idea there.

**Comment by winsock** [comment]
@jwise Also I have various other changes that may spark other things making sense over at this branch:
https://github.com/winsock/HoRNDIS/tree/test

Not confidant enough on some of the changes to submit PR's yet though, but might make you realize other things.
Side note: I think the subclassing of IOEthernetInterface into HoRNDISInterface is completely unnecessary to just set the MTU. Looking at the private method you had to override all it was is a stub to a public method that takes the object: https://github.com/winsock/HoRNDIS/commit/fc99c5619033950bead6c99008370640300cda67#diff-ca55b4153ff6514687d29fdcf8132b87R297

**Comment by winsock** [comment]
## [Blocked pending Kernel Panic resolution](https://github.com/jwise/HoRNDIS/issues/42#issuecomment-153777487).

**Comment by winsock** [comment]
Well this shouldn't really be open anymore now should it.

**Pull request closed without merging**
